export const mockProducts = [
  {
    id: "1",
    name: "Long Chair",
    price: 508,
    rating: 4.9,
    image: "/placeholder.svg",
    category: "Sofa",
    deal: "New",
  },
  {
    id: "2",
    name: "PureSpace Focus Duo",
    price: 320,
    rating: 4.8,
    image: "/placeholder.svg",
    category: "Chair",
    exclusive: true,
    description:
      "Sleek, minimalist design for ultimate productivity and comfort.",
  },
  {
    id: "3",
    name: "Great Value Deal",
    price: 250,
    rating: 4.9,
    image: "/placeholder.svg",
    category: "Table",
    deal: "Great Value",
    description: "Find Items On Sale With 50 - 75%",
  },
  {
    id: "4",
    name: "Minimalist Lamp",
    price: 80,
    rating: 4.7,
    image: "/placeholder.svg",
    category: "Lamps",
  },
  {
    id: "5",
    name: "Modern Dresser",
    price: 450,
    rating: 4.9,
    image: "/placeholder.svg",
    category: "Dressers",
  },
  {
    id: "6",
    name: "King Size Bed",
    price: 800,
    rating: 4.9,
    image: "/placeholder.svg",
    category: "Bed",
  },
];
